name: CI-PR
on: 
  pull_request:
    paths-ignore:
      - .github/**
      - README.md
      - .all-contributorsrc
      - CHANGELOG.md
      - LICENSE
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Set Variables
        run: |
          "BARE_REPOSITORY=$($env:GITHUB_REPOSITORY.split("/")[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Checkout
        uses: actions/checkout@v4
      - name: Modify TestModule1
        uses: ./
        with:
          path: tests\TestModule1\TestModule1.psd1
          version: 1.1.1
          copyright: (c) 2001 John Doe. All rights reserved.
          description: This is a test module.
          releaseNotes: Stuff changed.
          functionsToExport: Test-Function1,Test-Function2 
      - name: Modify TestModule2
        uses: ./
        with:
          path: tests\TestModule2
          version: 1.1.1-alpha1
          copyright: (c) YYYY John Doe. All rights reserved.
          functionsToExportPath: tests\TestModule2\public
      - name: Modify Test-Script1
        uses: ./
        with:
          path: tests\Test-Script1\Test-Script1.ps1
          version: 1.1.1
          copyright: (c) 2001 John Doe. All rights reserved.
          description: This is a test script.
          releaseNotes: Stuff changed. 
      - name: Modify Test-Script2
        uses: ./
        with:
          path: tests\Test-Script2
          version: 1.1.1-alpha1
          copyright: (c) YYYY John Doe. All rights reserved.
      - name: Run Pester Tests
        id: pester
        uses: zyborg/pester-tests-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: true
          tests_fail_step: true
          report_name: TestResults_${{ runner.os }}